/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DataCoin__factory } from "./DataCoin__factory";
export { ImageDAO__factory } from "./ImageDAO__factory";
