[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
filecoin-calibration = "${FILECOIN_CALIBRATION_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
filecoin-calibration = { key = "${FILSCAN_API_KEY}", url = "https://api.calibration.node.glif.io/rpc/v1" }