/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as imageDaoSol from "./ImageDAO.sol";
export type { imageDaoSol };
export type { Ledger } from "./Ledger";
